# ============================================================
#  Azure Storage Security Assessment
#  Generates: AzureStorage_Report.html
# ============================================================

# ── HTML Template Function ──────────────────────────────────
function Get-HtmlTemplate {
    param($Title, $SubName, $Date, $Rows, $Pass, $Fail, $Warn, $Total)
    $score = if ($Total -gt 0) { [math]::Round(($Pass / $Total) * 100) } else { 0 }
    $scoreColor = if ($score -ge 80) { "#00c87a" } elseif ($score -ge 60) { "#ffab40" } else { "#ff4d6d" }
    
    return @"
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <title>Azure Assessment - $Title</title>
    <link rel="icon" type="image/png" href="Screenshot_2026-03-10_201227-removebg-preview.png">
    <style>
        *{box-sizing:border-box;margin:0;padding:0}
        body{font-family:'Segoe UI',Arial,sans-serif;background:#0a0e1a;color:#e8eaf0;min-height:100vh;padding:30px}
        .container{max-width:1200px;margin:0 auto}
        .header{background:linear-gradient(135deg,#0078D4,#003f73);border-radius:16px;padding:32px 36px;margin-bottom:28px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:16px}
        .header h1{font-size:1.7rem;font-weight:800}
        .header p{font-size:0.85rem;opacity:.75;margin-top:6px}
        .score-circle{width:90px;height:90px;border-radius:50%;background:conic-gradient($scoreColor ${score}%, rgba(255,255,255,0.1) 0);display:flex;align-items:center;justify-content:center;flex-direction:column;position:relative}
        .score-inner{width:72px;height:72px;border-radius:50%;background:#0d1a2e;display:flex;align-items:center;justify-content:center;flex-direction:column;position:absolute}
        .score-num{font-size:1.3rem;font-weight:800;color:$scoreColor}
        .score-label{font-size:0.6rem;color:#8892a4;text-transform:uppercase;letter-spacing:.05em}
        .summary-cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:16px;margin-bottom:28px}
        .sum-card{background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:12px;padding:18px;text-align:center}
        .sum-card .num{font-size:2rem;font-weight:800;margin-bottom:4px}
        .sum-card .lbl{font-size:0.75rem;color:#8892a4;text-transform:uppercase;letter-spacing:.06em}
        .pass .num{color:#00c87a} .fail .num{color:#ff4d6d} .warn .num{color:#ffab40} .total .num{color:#50e6ff}
        table{width:100%;border-collapse:collapse;background:rgba(255,255,255,0.03);border-radius:12px;overflow:hidden}
        th{background:rgba(0,120,212,0.35);padding:12px 16px;text-align:left;font-size:0.78rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:#b0c4de}
        td{padding:11px 16px;font-size:0.85rem;border-bottom:1px solid rgba(255,255,255,0.06);vertical-align:top}
        tr:last-child td{border-bottom:none}
        tr:hover td{background:rgba(0,120,212,0.07)}
        .footer{text-align:center;margin-top:30px;font-size:0.8rem;color:#4a5568;padding:16px}
    </style>
</head>
<body>
<div class='container'>
    <div class='header'>
        <div><h1>☁ Azure $Title</h1><p>Subscription: $SubName &nbsp;|&nbsp; Generated: $Date</p></div>
        <div class='score-circle'><div class='score-inner'><span class='score-num'>${score}%</span><span class='score-label'>Score</span></div></div>
    </div>
    <div class='summary-cards'>
        <div class='sum-card total'><div class='num'>$Total</div><div class='lbl'>Total Checks</div></div>
        <div class='sum-card pass'><div class='num'>$Pass</div><div class='lbl'>Passed</div></div>
        <div class='sum-card fail'><div class='num'>$Fail</div><div class='lbl'>Failed</div></div>
        <div class='sum-card warn'><div class='num'>$Warn</div><div class='lbl'>Warnings</div></div>
    </div>
    <table>
        <thead><tr><th>Category</th><th>Check</th><th>Resource</th><th>Status</th><th>Details</th></tr></thead>
        <tbody>$Rows</tbody>
    </table>
    <div class='footer'>Azure Cloud Assessment Report &nbsp;|&nbsp; Generated by PowerShell Automation</div>
</div>
</body>
</html>
"@
}

# ── Assessment ──────────────────────────────────────────────
Write-Host "Checking for required Azure modules..." -ForegroundColor Cyan
if (-not (Get-Module -ListAvailable -Name Az.Storage)) {
    Write-Host "Installing Az.Storage module..." -ForegroundColor Yellow
    Install-Module -Name Az.Storage -AllowClobber -Force -Scope CurrentUser
    Import-Module -Name Az.Storage -Force
} else {
    # Check if Get-AzStorageAccountSasPolicy exists, if not update
    if (-not (Get-Command Get-AzStorageAccountSasPolicy -ErrorAction SilentlyContinue)) {
        Write-Host "Updating Az.Storage module to support SAS Policy cmdlets..." -ForegroundColor Yellow
        Update-Module -Name Az.Storage -Force -ErrorAction SilentlyContinue
        Import-Module -Name Az.Storage -Force
    }
}

Write-Host "Connecting to Azure..." -ForegroundColor Cyan
Connect-AzAccount -ErrorAction SilentlyContinue | Out-Null

$results = @()
$context = Get-AzContext
if (-not $context) { 
    Write-Host " ❌ No context found. Please ensure you are logged in." -ForegroundColor Red
    return 
}
$subName = $context.Subscription.Name
$subId   = $context.Subscription.Id
$date    = (Get-Date).ToUniversalTime().AddHours(5.5).ToString("yyyy-MM-dd HH:mm")

Write-Host "Running Storage checks on: $subName ($subId)" -ForegroundColor Yellow

# Add Context Row
$results += [PSCustomObject]@{ Category="Subscription"; Check="Active Context"; Resource=$subName; Status="PASS"; Details="Successfully identified subscription: $subId" }

try {

$accounts = Get-AzStorageAccount

foreach ($sa in $accounts){

$name = $sa.StorageAccountName
$rg = $sa.ResourceGroupName
$ctx = $sa.Context

# Secure Transfer Required
$results += [PSCustomObject]@{
Category="Storage"
Check="Secure transfer required"
Resource=$name
Status=if($sa.EnableHttpsTrafficOnly){"PASS"}else{"FAIL"}
Details=if($sa.EnableHttpsTrafficOnly){"HTTPS enforced"}else{"HTTP allowed"}
}

# Public Blob Access
$results += [PSCustomObject]@{
Category="Storage"
Check="Public blob access disabled"
Resource=$name
Status=if($sa.AllowBlobPublicAccess){"FAIL"}else{"PASS"}
Details=if($sa.AllowBlobPublicAccess){"Public blob access enabled"}else{"Public access disabled"}
}

# Minimum TLS
$results += [PSCustomObject]@{
Category="Storage"
Check="Minimum TLS version"
Resource=$name
Status=if($sa.MinimumTlsVersion -ge "TLS1_2"){"PASS"}else{"FAIL"}
Details="Configured TLS: $($sa.MinimumTlsVersion)"
}

# Network Rules
$results += [PSCustomObject]@{
Category="Storage"
Check="Storage firewall enabled"
Resource=$name
Status=if($sa.NetworkRuleSet.DefaultAction -eq "Deny"){"PASS"}else{"WARN"}
Details=if($sa.NetworkRuleSet.DefaultAction -eq "Deny"){"Restricted network access"}else{"Public access allowed"}
}

# Blob Encryption
$results += [PSCustomObject]@{
Category="Storage"
Check="Blob service encryption"
Resource=$name
Status=if($sa.Encryption.Services.Blob.Enabled){"PASS"}else{"FAIL"}
Details=if($sa.Encryption.Services.Blob.Enabled){"Blob encryption enabled"}else{"Encryption disabled"}
}

# File Encryption
$results += [PSCustomObject]@{
Category="Storage"
Check="File service encryption"
Resource=$name
Status=if($sa.Encryption.Services.File.Enabled){"PASS"}else{"FAIL"}
Details=if($sa.Encryption.Services.File.Enabled){"File encryption enabled"}else{"Encryption disabled"}
}

# Access Key Rotation
try{
$keys = Get-AzStorageAccountKey -ResourceGroupName $rg -Name $name

$rotationIssue = $false
$details = ""

foreach($key in $keys){
    if($key.CreationTime){
        $age = (Get-Date) - $key.CreationTime
        if($age.Days -gt 90){
            $rotationIssue = $true
        }
        $details += "$($key.KeyName) age: $($age.Days) days; "
    }
}

$status = if($rotationIssue){"FAIL"}else{"PASS"}

$results += [PSCustomObject]@{
Category="Storage"
Check="Storage access key rotation"
Resource=$name
Status=$status
Details=$details
}
}catch{
$results += [PSCustomObject]@{
Category="Storage"
Check="Storage access key rotation"
Resource=$name
Status="WARN"
Details="Unable to verify key rotation"
}
}

# Fetch SAS Policy (Safe execution)
$policy = $null
if (Get-Command Get-AzStorageAccountSasPolicy -ErrorAction SilentlyContinue) {
    try {
        $policy = Get-AzStorageAccountSasPolicy -ResourceGroupName $rg -StorageAccountName $name -ErrorAction Stop
    } catch {
        $policy = $null
    }
}

# SAS Expiry
if($policy -and $policy.SasExpirationPeriod){
    if([timespan]$policy.SasExpirationPeriod -le [timespan]"01:00:00"){
        $status="PASS"
    }
    else{
        $status="FAIL"
    }
    $detail="SAS expiration policy: $($policy.SasExpirationPeriod)"
}
else{
    $status="WARN"
    $detail="No SAS expiration policy configured"
}

$results += [PSCustomObject]@{
Category="Storage"
Check="SAS token expiry"
Resource=$name
Status=$status
Details=$detail
}

# SAS HTTPS
if($policy){
    $httpsOnly = $policy.Protocol -eq "Https"
    $results += [PSCustomObject]@{
    Category="Storage"
    Check="SAS HTTPS enforcement"
    Resource=$name
    Status=if($httpsOnly){"PASS"}else{"FAIL"}
    Details="SAS tokens must allow HTTPS only"
    }
}else{
    $results += [PSCustomObject]@{
    Category="Storage"
    Check="SAS HTTPS enforcement"
    Resource=$name
    Status="WARN"
    Details="Could not read SAS policy or no policy defined."
    }
}

# Blob Containers Public Access
try{

$containers = Get-AzStorageContainer -Context $ctx

foreach($c in $containers){

$results += [PSCustomObject]@{
Category="Storage"
Check="Blob container public access"
Resource="$name / $($c.Name)"
Status=if($c.PublicAccess -eq "Off"){"PASS"}else{"FAIL"}
Details=if($c.PublicAccess -eq "Off"){"Private container"}else{"Public access enabled"}
}

}

}catch{}

# Soft Delete
try{

$blobProp = Get-AzStorageServiceProperty -ServiceType Blob -Context $ctx

$results += [PSCustomObject]@{
Category="Storage"
Check="Blob soft delete"
Resource=$name
Status=if($blobProp.DeleteRetentionPolicy.Enabled){"PASS"}else{"WARN"}
Details=if($blobProp.DeleteRetentionPolicy.Enabled){"Enabled ($($blobProp.DeleteRetentionPolicy.Days) days)"}else{"Soft delete disabled"}
}

}catch{}

}

if(-not $accounts){

$results += [PSCustomObject]@{
Category="Storage"
Check="Storage accounts"
Resource="Subscription"
Status="INFO"
Details="No storage accounts found"
}

}

}catch{

$results += [PSCustomObject]@{
Category="Storage"
Check="Storage scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}
# ============================================================
# Azure Redis Cache Security Checks
# ============================================================

try {

$redisCaches = Get-AzRedisCache

if (-not $redisCaches -or $redisCaches.Count -eq 0) {

    $results += [PSCustomObject]@{
        Category="Redis"
        Check="Redis instances"
        Resource="Subscription"
        Status="INFO"
        Details="No Redis instances found"
    }

} else {

foreach ($cache in $redisCaches) {

$name = $cache.Name
$rg   = $cache.ResourceGroupName

# Get full resource (latest API for properties)
$resource = Get-AzResource -ResourceId $cache.Id -ApiVersion "2023-08-01" -ExpandProperties

# a. Entra Authentication
$entra = $resource.Properties.disableAccessKeyAuthentication
$results += [PSCustomObject]@{
Category="Redis"
Check="Microsoft Entra Authentication"
Resource=$name
Status=if($entra -eq $true){"PASS"}else{"FAIL"}
Details=if($entra){"Access key auth disabled (Entra enabled)"}else{"Access key auth enabled"}
}

# b. SSL Only
$nonSsl = $resource.Properties.enableNonSslPort
$results += [PSCustomObject]@{
Category="Redis"
Check="SSL only access"
Resource=$name
Status=if($nonSsl -eq $false){"PASS"}else{"FAIL"}
Details=if($nonSsl -eq $false){"Only SSL allowed"}else{"Non-SSL port enabled"}
}

# c. Minimum TLS
$tls = $resource.Properties.minimumTlsVersion
$results += [PSCustomObject]@{
Category="Redis"
Check="Minimum TLS version"
Resource=$name
Status=if($tls -in @("1.2","1.3")){"PASS"}else{"FAIL"}
Details="Configured TLS: $tls"
}

# d. Access Policies (Manual → WARN)
$policies = $resource.Properties.redisConfiguration."accessPolicies"
$results += [PSCustomObject]@{
Category="Redis"
Check="Access policies configured"
Resource=$name
Status=if($policies -and $policies.Count -gt 0){"PASS"}else{"WARN"}
Details=if($policies){"Policies configured"}else{"No access policies found (manual review)"}
}

# e. Managed Identity
$identityType = $resource.Identity.Type
$principalId  = $resource.Identity.PrincipalId
$results += [PSCustomObject]@{
Category="Redis"
Check="System assigned managed identity"
Resource=$name
Status=if($identityType -match "SystemAssigned" -and $principalId){"PASS"}else{"FAIL"}
Details=if($identityType){"Identity: $identityType"}else{"No identity assigned"}
}

# f. Public Network Access
$publicAccess = $resource.Properties.publicNetworkAccess
$isVnet = $resource.Properties.subnetId

$status = if($isVnet){"WARN"} elseif($publicAccess -eq "Disabled"){"PASS"} else {"FAIL"}
$detail = if($isVnet){"VNet deployment"} elseif($publicAccess -eq "Disabled"){"Public access disabled"} else {"Public access enabled"}

$results += [PSCustomObject]@{
Category="Redis"
Check="Public network access"
Resource=$name
Status=$status
Details=$detail
}

# g. Private Endpoint
$privateEndpoints = Get-AzPrivateEndpoint -ResourceGroupName $rg -ErrorAction SilentlyContinue

$matchedPE = $privateEndpoints | Where-Object {
    $_.PrivateLinkServiceConnections.PrivateLinkServiceId -eq $cache.Id
}

$results += [PSCustomObject]@{
Category="Redis"
Check="Private endpoint configured"
Resource=$name
Status=if($matchedPE){"PASS"}else{"FAIL"}
Details=if($matchedPE){"Private endpoint in use"}else{"No private endpoint"}
}

# h. Customer Managed Key (Enterprise)
try {
$enterprise = Get-AzRedisEnterpriseCache -Name $name -ResourceGroupName $rg -ErrorAction SilentlyContinue

if($enterprise){
    $cmk = $enterprise.EnableCustomerManagedKey
    $results += [PSCustomObject]@{
    Category="Redis"
    Check="Customer managed key (CMK)"
    Resource=$name
    Status=if($cmk){"PASS"}else{"FAIL"}
    Details=if($cmk){"CMK enabled"}else{"Using Microsoft-managed keys"}
    }
}
}catch{}

# i. Access Keys Disabled
$accessKeyDisabled = $cache.DisableAccessKeyAuthentication
$results += [PSCustomObject]@{
Category="Redis"
Check="Access key authentication disabled"
Resource=$name
Status=if($accessKeyDisabled){"PASS"}else{"FAIL"}
Details=if($accessKeyDisabled){"Access keys disabled"}else{"Access keys enabled"}
}

# j. Update Channel
$updateChannel = $cache.UpdateChannel
$results += [PSCustomObject]@{
Category="Redis"
Check="Update channel stable"
Resource=$name
Status=if($updateChannel -eq "Stable"){"PASS"}else{"WARN"}
Details="Channel: $updateChannel"
}

}

}

}catch{

$results += [PSCustomObject]@{
Category="Redis"
Check="Redis scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}
# ============================================================
# Azure Cosmos DB Security Checks
# ============================================================

try {

$cosmosAccounts = Get-AzResource -ExpandProperties | Where-Object {
    $_.ResourceType -eq "Microsoft.DocumentDB/databaseAccounts" -or
    $_.ResourceType -eq "Microsoft.DocumentDB/mongoClusters"
}

if (-not $cosmosAccounts -or $cosmosAccounts.Count -eq 0) {

    $results += [PSCustomObject]@{
        Category="CosmosDB"
        Check="Cosmos DB accounts"
        Resource="Subscription"
        Status="INFO"
        Details="No Cosmos DB accounts found"
    }

} else {

foreach ($account in $cosmosAccounts) {

$name = $account.Name
$type = $account.ResourceType

# a. Firewall limited to selected networks
$vnetFilter = $account.Properties.isVirtualNetworkFilterEnabled
$results += [PSCustomObject]@{
Category="CosmosDB"
Check="Firewall restricted to selected networks"
Resource=$name
Status=if($vnetFilter -eq $true){"PASS"}else{"FAIL"}
Details=if($vnetFilter){"VNet filtering enabled"}else{"Open to all networks"}
}

# b. Private Endpoint
$privateEndpoints = Get-AzPrivateEndpoint -ErrorAction SilentlyContinue
$matchedPE = $privateEndpoints | Where-Object {
    $_.PrivateLinkServiceConnections.PrivateLinkServiceId -eq $account.ResourceId
}

$status = if($type -eq "Microsoft.DocumentDB/mongoClusters"){"WARN"} elseif($matchedPE){"PASS"} else {"FAIL"}
$detail = if($type -eq "Microsoft.DocumentDB/mongoClusters"){"Not Applicable (Mongo vCore)"} elseif($matchedPE){"Private endpoint configured"} else {"No private endpoint"}

$results += [PSCustomObject]@{
Category="CosmosDB"
Check="Private endpoint configured"
Resource=$name
Status=$status
Details=$detail
}

# c. Disable Local Auth
if ($type -eq "Microsoft.DocumentDB/mongoClusters") {
    $results += [PSCustomObject]@{
    Category="CosmosDB"
    Check="Local authentication disabled"
    Resource=$name
    Status="WARN"
    Details="Not Applicable (Mongo vCore)"
    }
} else {
    $disableLocalAuth = $account.Properties.disableLocalAuth
    $results += [PSCustomObject]@{
    Category="CosmosDB"
    Check="Local authentication disabled"
    Resource=$name
    Status=if($disableLocalAuth){"PASS"}else{"FAIL"}
    Details=if($disableLocalAuth){"Local auth disabled"}else{"Local auth enabled"}
    }
}

# d. Public Network Access
if ($type -eq "Microsoft.DocumentDB/mongoClusters") {
    $results += [PSCustomObject]@{
    Category="CosmosDB"
    Check="Public network access disabled"
    Resource=$name
    Status="WARN"
    Details="Not Applicable (Mongo vCore)"
    }
} else {
    $publicAccess = $account.Properties.publicNetworkAccess
    $results += [PSCustomObject]@{
    Category="CosmosDB"
    Check="Public network access disabled"
    Resource=$name
    Status=if($publicAccess -eq "Disabled"){"PASS"}else{"FAIL"}
    Details="Public Access: $publicAccess"
    }
}

# e. Customer Managed Key
if ($type -eq "Microsoft.DocumentDB/mongoClusters") {
    $results += [PSCustomObject]@{
    Category="CosmosDB"
    Check="Customer managed key (CMK)"
    Resource=$name
    Status="WARN"
    Details="Not Applicable (Mongo vCore)"
    }
} else {
    $cmk = $account.Properties.keyVaultKeyUri
    $results += [PSCustomObject]@{
    Category="CosmosDB"
    Check="Customer managed key (CMK)"
    Resource=$name
    Status=if($cmk){"PASS"}else{"FAIL"}
    Details=if($cmk){"CMK configured"}else{"Using Microsoft-managed keys"}
    }
}

# f. Firewall not allowing all traffic
if ($type -eq "Microsoft.DocumentDB/mongoClusters") {
    $results += [PSCustomObject]@{
    Category="CosmosDB"
    Check="Firewall does not allow all traffic"
    Resource=$name
    Status="WARN"
    Details="Not Applicable (Mongo vCore)"
    }
} else {
    $ipRules = $account.Properties.ipRules
    $allowAll = $false

    if ($ipRules) {
        foreach ($ip in $ipRules) {
            if ($ip.ipAddressOrRange -eq "0.0.0.0") {
                $allowAll = $true
                break
            }
        }
    }

    $results += [PSCustomObject]@{
    Category="CosmosDB"
    Check="Firewall does not allow all traffic"
    Resource=$name
    Status=if($allowAll){"FAIL"}else{"PASS"}
    Details=if($allowAll){"Allows all IPs"}else{"Restricted IP rules"}
    }
}

}

}

}catch{

$results += [PSCustomObject]@{
Category="CosmosDB"
Check="Cosmos DB scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}

# ============================================================
# Azure Data Factory Security Checks
# ============================================================

try {

$dataFactories = Get-AzResource -ResourceType "Microsoft.DataFactory/factories" -ExpandProperties

if (-not $dataFactories -or $dataFactories.Count -eq 0) {

    $results += [PSCustomObject]@{
        Category="DataFactory"
        Check="Data Factory instances"
        Resource="Subscription"
        Status="INFO"
        Details="No Data Factory instances found"
    }

} else {

foreach ($df in $dataFactories) {

$name = $df.Name
$resourceId = $df.ResourceId
$rg = ($resourceId -split "/")[4]

# a. Customer Managed Key
$cmk = $df.Properties.encryption.keyVaultProperties.keyUri
$results += [PSCustomObject]@{
Category="DataFactory"
Check="Customer managed key (CMK)"
Resource=$name
Status=if($cmk){"PASS"}else{"FAIL"}
Details=if($cmk){"CMK configured"}else{"Using Microsoft-managed keys"}
}

# b. Managed Identity
$identityType = $df.Identity.Type
$principalId  = $df.Identity.PrincipalId

$results += [PSCustomObject]@{
Category="DataFactory"
Check="Managed identity enabled"
Resource=$name
Status=if($identityType -and ($identityType -match "SystemAssigned|UserAssigned")){"PASS"}else{"FAIL"}
Details=if($identityType){"Identity: $identityType"}else{"No identity configured"}
}

# c. Azure Key Vault usage (Linked Services)
try {

$linkedServices = Get-AzDataFactoryV2LinkedService `
    -ResourceGroupName $rg `
    -DataFactoryName $name `
    -ErrorAction SilentlyContinue

$usesKeyVault = $false

if ($linkedServices) {
    foreach ($ls in $linkedServices) {

        if ($ls.Properties.Type -eq "AzureKeyVault") {
            $usesKeyVault = $true
            break
        }

        if ($ls.Properties.TypeProperties -match "keyVault") {
            $usesKeyVault = $true
            break
        }
    }
}

$results += [PSCustomObject]@{
Category="DataFactory"
Check="Uses Azure Key Vault for secrets"
Resource=$name
Status=if($usesKeyVault){"PASS"}else{"WARN"}
Details=if($usesKeyVault){"Key Vault used in linked services"}else{"No Key Vault usage detected"}
}

}catch{
$results += [PSCustomObject]@{
Category="DataFactory"
Check="Uses Azure Key Vault for secrets"
Resource=$name
Status="WARN"
Details="Unable to verify linked services"
}
}

# d. RBAC Role Assignments
try {

$roles = Get-AzRoleAssignment -Scope $resourceId -ErrorAction SilentlyContinue

$results += [PSCustomObject]@{
Category="DataFactory"
Check="RBAC roles assigned"
Resource=$name
Status=if($roles -and $roles.Count -gt 0){"PASS"}else{"WARN"}
Details=if($roles){"RBAC roles configured"}else{"No RBAC roles found"}
}

}catch{
$results += [PSCustomObject]@{
Category="DataFactory"
Check="RBAC roles assigned"
Resource=$name
Status="WARN"
Details="Unable to verify RBAC roles"
}
}

}

}

}catch{

$results += [PSCustomObject]@{
Category="DataFactory"
Check="Data Factory scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}

# ============================================================
# Azure MySQL Flexible Server Security Checks
# ============================================================

try {

$servers = Get-AzResource -ResourceType "Microsoft.DBforMySQL/flexibleServers"

if (-not $servers -or $servers.Count -eq 0) {

    $results += [PSCustomObject]@{
        Category="MySQL"
        Check="MySQL servers"
        Resource="Subscription"
        Status="INFO"
        Details="No Azure Database for MySQL servers found"
    }

} else {

foreach ($server in $servers) {

$name = $server.Name
$rg   = $server.ResourceGroupName
$resourceId = $server.ResourceId

# Get full details
$details = Get-AzResource -ResourceId $resourceId -ExpandProperties

# a. CMK Encryption
$encType = $details.Properties.dataEncryption.type
$results += [PSCustomObject]@{
Category="MySQL"
Check="Customer managed key (CMK)"
Resource=$name
Status=if($encType -eq "AzureKeyVault"){"PASS"}else{"FAIL"}
Details="Encryption type: $encType"
}

# b. Entra-only Authentication
$auth = $details.Properties.authConfig
$results += [PSCustomObject]@{
Category="MySQL"
Check="Entra-only authentication"
Resource=$name
Status=if($auth.activeDirectoryAuth -eq "Enabled" -and $auth.passwordAuth -eq "Disabled"){"PASS"}else{"FAIL"}
Details="AD Auth: $($auth.activeDirectoryAuth), Password Auth: $($auth.passwordAuth)"
}

# c. Public Network Access
$publicAccess = $details.Properties.network.publicNetworkAccess
$results += [PSCustomObject]@{
Category="MySQL"
Check="Public network access disabled"
Resource=$name
Status=if($publicAccess -eq "Disabled"){"PASS"}else{"FAIL"}
Details="Public Access: $publicAccess"
}

# d. Private Endpoint
$peConnections = Get-AzPrivateEndpointConnection -PrivateLinkResourceId $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="MySQL"
Check="Private endpoint configured"
Resource=$name
Status=if($peConnections){"PASS"}else{"FAIL"}
Details=if($peConnections){"Private endpoint exists"}else{"No private endpoint"}
}

# e. audit_log_enabled
try {
$param = Get-AzMySqlFlexibleServerConfiguration -ResourceGroupName $rg -ServerName $name -Name "audit_log_enabled" -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="MySQL"
Check="Audit log enabled"
Resource=$name
Status=if($param.Value -eq "ON"){"PASS"}else{"FAIL"}
Details="Value: $($param.Value)"
}
}catch{}

# f. audit_log_events (CONNECTION)
try {
$param = Get-AzMySqlFlexibleServerConfiguration -ResourceGroupName $rg -ServerName $name -Name "audit_log_events" -ErrorAction SilentlyContinue
$value = $param.Value

$results += [PSCustomObject]@{
Category="MySQL"
Check="Audit log events include CONNECTION"
Resource=$name
Status=if($value -and $value.ToUpper().Contains("CONNECTION")){"PASS"}else{"FAIL"}
Details="Value: $value"
}
}catch{}

# g. error_server_log_file
try {
$param = Get-AzMySqlFlexibleServerConfiguration -ResourceGroupName $rg -ServerName $name -Name "error_server_log_file" -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="MySQL"
Check="Error server logging enabled"
Resource=$name
Status=if($param.Value -eq "ON"){"PASS"}else{"FAIL"}
Details="Value: $($param.Value)"
}
}catch{}

# h. require_secure_transport
try {
$param = Get-AzMySqlFlexibleServerConfiguration -ResourceGroupName $rg -ServerName $name -Name "require_secure_transport" -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="MySQL"
Check="Secure transport enforced"
Resource=$name
Status=if($param.Value -eq "ON"){"PASS"}else{"FAIL"}
Details="Value: $($param.Value)"
}
}catch{}

# i. TLS Version
try {
$param = Get-AzMySqlFlexibleServerConfiguration -ResourceGroupName $rg -ServerName $name -Name "tls_version" -ErrorAction SilentlyContinue
$value = $param.Value

$valid = ($value -match "TLSv1.2|TLSv1.3") -and ($value -notmatch "TLSv1[^\.]|TLSv1\.1")

$results += [PSCustomObject]@{
Category="MySQL"
Check="TLS version secure"
Resource=$name
Status=if($valid){"PASS"}else{"FAIL"}
Details="Value: $value"
}
}catch{}

}

}

}catch{

$results += [PSCustomObject]@{
Category="MySQL"
Check="MySQL scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}


# ============================================================
# Azure PostgreSQL Flexible Server Security Checks
# ============================================================

try {

$servers = Get-AzResource -ResourceType "Microsoft.DBforPostgreSQL/flexibleServers"

if (-not $servers -or $servers.Count -eq 0) {

    $results += [PSCustomObject]@{
        Category="PostgreSQL"
        Check="PostgreSQL servers"
        Resource="Subscription"
        Status="INFO"
        Details="No PostgreSQL servers found"
    }

} else {

foreach ($server in $servers) {

$name = $server.Name
$rg   = $server.ResourceGroupName
$resourceId = $server.ResourceId

$details = Get-AzResource -ResourceId $resourceId -ExpandProperties

# a. CMK Encryption
$type = $details.Properties.dataEncryption.type
$results += [PSCustomObject]@{
Category="PostgreSQL"
Check="Customer managed key (CMK)"
Resource=$name
Status=if($type -eq "AzureKeyVault"){"PASS"}else{"FAIL"}
Details="Encryption type: $type"
}

# b. Entra-only Authentication
$auth = $details.Properties.authConfig
$results += [PSCustomObject]@{
Category="PostgreSQL"
Check="Entra-only authentication"
Resource=$name
Status=if($auth.activeDirectoryAuth -eq "Enabled" -and $auth.passwordAuth -eq "Disabled"){"PASS"}else{"FAIL"}
Details="AD Auth: $($auth.activeDirectoryAuth), Password Auth: $($auth.passwordAuth)"
}

# c. Public Network Access
$publicAccess = $details.Properties.network.publicNetworkAccess
$results += [PSCustomObject]@{
Category="PostgreSQL"
Check="Public network access disabled"
Resource=$name
Status=if($publicAccess -eq "Disabled"){"PASS"}else{"FAIL"}
Details="Public Access: $publicAccess"
}

# d. Private Endpoint
$pe = Get-AzPrivateEndpointConnection -PrivateLinkResourceId $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="PostgreSQL"
Check="Private endpoint configured"
Resource=$name
Status=if($pe){"PASS"}else{"FAIL"}
Details=if($pe){"Private endpoint exists"}else{"No private endpoint"}
}

# e. connection_throttle.enable
try {
$param = Get-AzPostgreSqlFlexibleServerConfiguration -ResourceGroupName $rg -ServerName $name -Name "connection_throttle.enable" -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="PostgreSQL"
Check="Connection throttle enabled"
Resource=$name
Status=if($param.Value -eq "ON"){"PASS"}else{"FAIL"}
Details="Value: $($param.Value)"
}
}catch{}

# f. logfiles.retention_days > 3
try {
$param = Get-AzPostgreSqlFlexibleServerConfiguration -ResourceGroupName $rg -ServerName $name -Name "logfiles.retention_days" -ErrorAction SilentlyContinue
$val = [int]$param.Value

$results += [PSCustomObject]@{
Category="PostgreSQL"
Check="Log retention > 3 days"
Resource=$name
Status=if($val -gt 3){"PASS"}else{"FAIL"}
Details="Days: $val"
}
}catch{}

# g. log_checkpoints
try {
$param = Get-AzPostgreSqlFlexibleServerConfiguration -ResourceGroupName $rg -ServerName $name -Name "log_checkpoints" -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="PostgreSQL"
Check="Log checkpoints enabled"
Resource=$name
Status=if($param.Value -eq "ON"){"PASS"}else{"FAIL"}
Details="Value: $($param.Value)"
}
}catch{}

# h. log_disconnections
try {
$param = Get-AzPostgreSqlFlexibleServerConfiguration -ResourceGroupName $rg -ServerName $name -Name "log_disconnections" -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="PostgreSQL"
Check="Log disconnections enabled"
Resource=$name
Status=if($param.Value -eq "ON"){"PASS"}else{"FAIL"}
Details="Value: $($param.Value)"
}
}catch{}

# i. log_connections
try {
$param = Get-AzPostgreSqlFlexibleServerConfiguration -ResourceGroupName $rg -ServerName $name -Name "log_connections" -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="PostgreSQL"
Check="Log connections enabled"
Resource=$name
Status=if($param.Value -eq "ON"){"PASS"}else{"FAIL"}
Details="Value: $($param.Value)"
}
}catch{}

# j. require_secure_transport
try {
$param = Get-AzPostgreSqlFlexibleServerConfiguration -ResourceGroupName $rg -ServerName $name -Name "require_secure_transport" -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="PostgreSQL"
Check="Secure transport enforced"
Resource=$name
Status=if($param.Value -eq "ON"){"PASS"}else{"FAIL"}
Details="Value: $($param.Value)"
}
}catch{}

# k. TLS Version
try {
$param = Get-AzPostgreSqlFlexibleServerConfiguration -ResourceGroupName $rg -ServerName $name -Name "ssl_min_protocol_version" -ErrorAction SilentlyContinue
$value = $param.Value

$valid = ($value -match "TLSv1.2|TLSv1.3") -and ($value -notmatch "TLSv1[^\.]|TLSv1\.1")

$results += [PSCustomObject]@{
Category="PostgreSQL"
Check="TLS version secure"
Resource=$name
Status=if($valid){"PASS"}else{"FAIL"}
Details="Value: $value"
}
}catch{}

}

}

}catch{

$results += [PSCustomObject]@{
Category="PostgreSQL"
Check="PostgreSQL scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}


# ============================================================
# Azure Database Migration Service Security Checks
# ============================================================

try {

$services = Get-AzResource -ResourceType "Microsoft.DataMigration/services"

if (-not $services -or $services.Count -eq 0) {

    $results += [PSCustomObject]@{
        Category="DMS"
        Check="DMS instances"
        Resource="Subscription"
        Status="INFO"
        Details="No Azure DMS instances found"
    }

} else {

foreach ($svc in $services) {

$name = $svc.Name
$resourceId = $svc.ResourceId

$details = Get-AzResource -ResourceId $resourceId -ExpandProperties

# Public Access
$publicAccess = $details.Properties.publicNetworkAccess
$results += [PSCustomObject]@{
Category="DMS"
Check="Public network access disabled"
Resource=$name
Status=if($publicAccess -eq "Disabled"){"PASS"}else{"FAIL"}
Details="Public Access: $publicAccess"
}

# Managed Identity
$identity = $details.Identity.Type
$results += [PSCustomObject]@{
Category="DMS"
Check="Managed identity enabled"
Resource=$name
Status=if($identity){"PASS"}else{"FAIL"}
Details=if($identity){"Identity: $identity"}else{"No identity"}
}

# Private Endpoint
$pe = Get-AzPrivateEndpointConnection -PrivateLinkResourceId $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="DMS"
Check="Private endpoint configured"
Resource=$name
Status=if($pe){"PASS"}else{"FAIL"}
Details=if($pe){"Private endpoint exists"}else{"No private endpoint"}
}

# Diagnostic Logs
$diag = Get-AzDiagnosticSetting -ResourceId $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="DMS"
Check="Diagnostic logs enabled"
Resource=$name
Status=if($diag){"PASS"}else{"WARN"}
Details=if($diag){"Diagnostics configured"}else{"No diagnostics"}
}

# RBAC
$roles = Get-AzRoleAssignment -Scope $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="DMS"
Check="RBAC configured"
Resource=$name
Status=if($roles){"PASS"}else{"WARN"}
Details=if($roles){"Roles assigned"}else{"No RBAC roles"}
}

}

}

}catch{

$results += [PSCustomObject]@{
Category="DMS"
Check="DMS scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}



# ============================================================
# Azure SQL Security Checks
# ============================================================

try {

$servers = Get-AzSqlServer

if (-not $servers) {

    $results += [PSCustomObject]@{
        Category="SQL"
        Check="SQL Servers"
        Resource="Subscription"
        Status="INFO"
        Details="No SQL Servers found"
    }

} else {

foreach ($server in $servers) {

$name = $server.ServerName
$rg   = $server.ResourceGroupName

# a. Auditing Enabled
$audit = Get-AzSqlServerAudit -ResourceGroupName $rg -ServerName $name
$enabled = ($audit.BlobStorageTargetState -eq "Enabled" -or 
            $audit.LogAnalyticsTargetState -eq "Enabled" -or 
            $audit.EventHubTargetState -eq "Enabled")

$results += [PSCustomObject]@{
Category="SQL"
Check="Auditing enabled"
Resource=$name
Status=if($enabled){"PASS"}else{"FAIL"}
Details="Audit configured"
}

# b. Public Access Disabled
$results += [PSCustomObject]@{
Category="SQL"
Check="Public network access disabled"
Resource=$name
Status=if($server.PublicNetworkAccess -eq "Disabled"){"PASS"}else{"FAIL"}
Details="Public Access: $($server.PublicNetworkAccess)"
}

# c. Firewall Rules
$rules = Get-AzSqlServerFirewallRule -ResourceGroupName $rg -ServerName $name
$open = $false

foreach ($rule in $rules) {
    if ($rule.StartIpAddress -eq "0.0.0.0" -or $rule.EndIpAddress -eq "255.255.255.255") {
        $open = $true
    }
}

$results += [PSCustomObject]@{
Category="SQL"
Check="Firewall not overly permissive"
Resource=$name
Status=if($open){"FAIL"}else{"PASS"}
Details=if($open){"Allows all IPs"}else{"Restricted rules"}
}

# d. TDE Protector CMK
$tde = Get-AzSqlServerTransparentDataEncryptionProtector -ResourceGroupName $rg -ServerName $name
$results += [PSCustomObject]@{
Category="SQL"
Check="TDE protector uses CMK"
Resource=$name
Status=if($tde.Type -eq "AzureKeyVault"){"PASS"}else{"FAIL"}
Details="Type: $($tde.Type)"
}

# e. Entra Authentication
$ad = Get-AzSqlServerActiveDirectoryAdministrator -ResourceGroupName $rg -ServerName $name -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="SQL"
Check="Entra authentication configured"
Resource=$name
Status=if($ad){"PASS"}else{"FAIL"}
Details=if($ad){"Configured"}else{"Not configured"}
}

# f. DB TDE Enabled
$dbs = Get-AzSqlDatabase -ResourceGroupName $rg -ServerName $name

foreach ($db in $dbs) {

if ($db.DatabaseName -ne "master") {

$tdeDb = Get-AzSqlDatabaseTransparentDataEncryption -ResourceGroupName $rg -ServerName $name -DatabaseName $db.DatabaseName

$results += [PSCustomObject]@{
Category="SQL"
Check="Database encryption enabled"
Resource="$name / $($db.DatabaseName)"
Status=if($tdeDb.State -eq "Enabled"){"PASS"}else{"FAIL"}
Details="TDE: $($tdeDb.State)"
}

}

}

# g. Audit Retention
$results += [PSCustomObject]@{
Category="SQL"
Check="Audit retention > 90 days"
Resource=$name
Status=if($audit.RetentionInDays -gt 90 -or $audit.RetentionInDays -eq 0){"PASS"}else{"FAIL"}
Details="Days: $($audit.RetentionInDays)"
}

# h. TLS Version
$results += [PSCustomObject]@{
Category="SQL"
Check="TLS version secure"
Resource=$name
Status=if($server.MinimalTlsVersion -ge "1.2"){"PASS"}else{"FAIL"}
Details="TLS: $($server.MinimalTlsVersion)"
}

}

}

}catch{

$results += [PSCustomObject]@{
Category="SQL"
Check="SQL scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}


# ============================================================
# Azure SQL Managed Instance Security Checks
# ============================================================

try {

$instances = Get-AzSqlInstance

if (-not $instances -or $instances.Count -eq 0) {

    $results += [PSCustomObject]@{
        Category="SQLMI"
        Check="SQL Managed Instances"
        Resource="Subscription"
        Status="INFO"
        Details="No SQL Managed Instances found"
    }

} else {

foreach ($mi in $instances) {

$name = $mi.Name
$resourceId = $mi.Id

# Public Endpoint
$results += [PSCustomObject]@{
Category="SQLMI"
Check="Public endpoint disabled"
Resource=$name
Status=if($mi.PublicDataEndpointEnabled -eq $false){"PASS"}else{"FAIL"}
Details="Public Endpoint: $($mi.PublicDataEndpointEnabled)"
}

# Managed Identity
$results += [PSCustomObject]@{
Category="SQLMI"
Check="Managed identity enabled"
Resource=$name
Status=if($mi.Identity.Type){"PASS"}else{"FAIL"}
Details="Identity: $($mi.Identity.Type)"
}

# Private Network (VNet)
$results += [PSCustomObject]@{
Category="SQLMI"
Check="Deployed in private network (VNet)"
Resource=$name
Status=if($mi.SubnetId){"PASS"}else{"FAIL"}
Details="Subnet: $($mi.SubnetId)"
}

# Diagnostic Logs
$diag = Get-AzDiagnosticSetting -ResourceId $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="SQLMI"
Check="Diagnostic logs enabled"
Resource=$name
Status=if($diag){"PASS"}else{"WARN"}
Details=if($diag){"Diagnostics configured"}else{"No diagnostics"}
}

# RBAC
$roles = Get-AzRoleAssignment -Scope $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="SQLMI"
Check="RBAC configured"
Resource=$name
Status=if($roles){"PASS"}else{"WARN"}
Details=if($roles){"Roles assigned"}else{"No RBAC roles"}
}

# TLS
$results += [PSCustomObject]@{
Category="SQLMI"
Check="TLS version secure"
Resource=$name
Status=if($mi.MinimalTlsVersion -eq "1.2"){"PASS"}else{"FAIL"}
Details="TLS: $($mi.MinimalTlsVersion)"
}

}

}

}catch{

$results += [PSCustomObject]@{
Category="SQLMI"
Check="SQL MI scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}

# ============================================================
# SQL Server on Azure VM Security Checks
# ============================================================

try {

$vms = Get-AzVM | Where-Object {
    $_.StorageProfile.ImageReference.Offer -like "*SQL*"
}

if (-not $vms -or $vms.Count -eq 0) {

    $results += [PSCustomObject]@{
        Category="SQLVM"
        Check="SQL VMs"
        Resource="Subscription"
        Status="INFO"
        Details="No SQL Server VMs found"
    }

} else {

foreach ($vm in $vms) {

$name = $vm.Name
$rg   = $vm.ResourceGroupName
$resourceId = $vm.Id

# NIC
$nic = Get-AzNetworkInterface -ResourceGroupName $rg | Where-Object {
    $_.VirtualMachine.Id -eq $vm.Id
}

# Public IP
$publicIP = $false
foreach ($ip in $nic.IpConfigurations) {
    if ($ip.PublicIpAddress) { $publicIP = $true }
}

$results += [PSCustomObject]@{
Category="SQLVM"
Check="No public IP"
Resource=$name
Status=if($publicIP){"FAIL"}else{"PASS"}
Details=if($publicIP){"Public IP attached"}else{"Private only"}
}

# Managed Identity
$results += [PSCustomObject]@{
Category="SQLVM"
Check="Managed identity enabled"
Resource=$name
Status=if($vm.Identity.Type){"PASS"}else{"FAIL"}
Details="Identity: $($vm.Identity.Type)"
}

# NSG
$results += [PSCustomObject]@{
Category="SQLVM"
Check="NSG attached"
Resource=$name
Status=if($nic.NetworkSecurityGroup){"PASS"}else{"FAIL"}
Details="NSG: $($nic.NetworkSecurityGroup.Id)"
}

# Disk Encryption
$enc = Get-AzVMDiskEncryptionStatus -ResourceGroupName $rg -VMName $name -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="SQLVM"
Check="Disk encryption enabled"
Resource=$name
Status=if($enc.OsVolumeEncrypted -eq "Encrypted"){"PASS"}else{"FAIL"}
Details="OS Disk: $($enc.OsVolumeEncrypted)"
}

# Diagnostics
$diag = Get-AzDiagnosticSetting -ResourceId $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="SQLVM"
Check="Diagnostic logs enabled"
Resource=$name
Status=if($diag){"PASS"}else{"WARN"}
Details=if($diag){"Configured"}else{"Not configured"}
}

# RBAC
$roles = Get-AzRoleAssignment -Scope $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="SQLVM"
Check="RBAC configured"
Resource=$name
Status=if($roles){"PASS"}else{"WARN"}
Details=if($roles){"Roles assigned"}else{"No roles"}
}

}

}

}catch{

$results += [PSCustomObject]@{
Category="SQLVM"
Check="SQL VM scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}

# ============================================================
# Storage Advanced Security Checks
# ============================================================

try {

$accounts = Get-AzStorageAccount

foreach ($acc in $accounts) {

$name = $acc.StorageAccountName
$resourceId = $acc.Id

# Private Endpoint
$pe = Get-AzPrivateEndpointConnection -PrivateLinkResourceId $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="Storage"
Check="Private endpoint configured"
Resource=$name
Status=if($pe){"PASS"}else{"FAIL"}
Details=if($pe){"Private endpoint exists"}else{"No private endpoint"}
}

# Managed Identity
$results += [PSCustomObject]@{
Category="Storage"
Check="Managed identity enabled"
Resource=$name
Status=if($acc.Identity.Type){"PASS"}else{"WARN"}
Details="Identity: $($acc.Identity.Type)"
}

# Diagnostic Logs
$diag = Get-AzDiagnosticSetting -ResourceId $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="Storage"
Check="Diagnostic logs enabled"
Resource=$name
Status=if($diag){"PASS"}else{"WARN"}
Details=if($diag){"Configured"}else{"Not configured"}
}

# RBAC
$roles = Get-AzRoleAssignment -Scope $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="Storage"
Check="RBAC configured"
Resource=$name
Status=if($roles){"PASS"}else{"WARN"}
Details=if($roles){"Roles assigned"}else{"No roles"}
}

}

}catch{

$results += [PSCustomObject]@{
Category="Storage"
Check="Advanced storage scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}

# ============================================================
# Azure Kubernetes Service (AKS) Security Checks
# ============================================================

try {

$clusters = Get-AzAksCluster

if (-not $clusters -or $clusters.Count -eq 0) {

    $results += [PSCustomObject]@{
        Category="AKS"
        Check="AKS Clusters"
        Resource="Subscription"
        Status="INFO"
        Details="No AKS clusters found"
    }

} else {

foreach ($cluster in $clusters) {

$name = $cluster.Name
$rg   = $cluster.ResourceGroupName
$resourceId = $cluster.Id

# Private Cluster
$results += [PSCustomObject]@{
Category="AKS"
Check="Private cluster"
Resource=$name
Status=if($cluster.NetworkProfile.PrivateCluster){"PASS"}else{"FAIL"}
Details=if($cluster.NetworkProfile.PrivateCluster){"Private cluster enabled"}else{"Public cluster"}
}

# RBAC
$roles = Get-AzRoleAssignment -Scope $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="AKS"
Check="RBAC configured"
Resource=$name
Status=if($roles){"PASS"}else{"WARN"}
Details=if($roles){"Roles assigned"}else{"No roles"}
}

# Diagnostic Logs
$diag = Get-AzDiagnosticSetting -ResourceId $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="AKS"
Check="Diagnostic logs enabled"
Resource=$name
Status=if($diag){"PASS"}else{"WARN"}
Details=if($diag){"Configured"}else{"Not configured"}
}

# Managed Identity
$results += [PSCustomObject]@{
Category="AKS"
Check="Managed identity enabled"
Resource=$name
Status=if($cluster.Identity.Type){"PASS"}else{"FAIL"}
Details="Identity: $($cluster.Identity.Type)"
}

# Network Policy
$results += [PSCustomObject]@{
Category="AKS"
Check="Network policy enabled"
Resource=$name
Status=if($cluster.NetworkProfile.NetworkPolicy){"PASS"}else{"WARN"}
Details="Policy: $($cluster.NetworkProfile.NetworkPolicy)"
}

# Auto-upgrade
$results += [PSCustomObject]@{
Category="AKS"
Check="Auto-upgrade enabled"
Resource=$name
Status=if($cluster.AutoUpgradeProfile.Enabled){"PASS"}else{"WARN"}
Details="Auto-upgrade: $($cluster.AutoUpgradeProfile.Enabled)"
}

} # end foreach cluster

} # end else

}catch{

$results += [PSCustomObject]@{
Category="AKS"
Check="AKS scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}

# ============================================================
# Azure Managed Instance for Apache Cassandra Security Checks
# ============================================================

try {

$clusters = Get-AzResource -ResourceType "Microsoft.DocumentDB/cassandraClusters"

if (-not $clusters -or $clusters.Count -eq 0) {

    $results += [PSCustomObject]@{
        Category="Cassandra"
        Check="Cassandra clusters"
        Resource="Subscription"
        Status="INFO"
        Details="No Cassandra clusters found"
    }

} else {

foreach ($cluster in $clusters) {

$name = $cluster.Name
$resourceId = $cluster.ResourceId

$details = Get-AzResource -ResourceId $resourceId -ExpandProperties

# Public Access
$publicAccess = $details.Properties.publicNetworkAccess
$results += [PSCustomObject]@{
Category="Cassandra"
Check="Public network access disabled"
Resource=$name
Status=if($publicAccess -eq "Disabled"){"PASS"}else{"FAIL"}
Details="Public Access: $publicAccess"
}

# Private Endpoint
$pe = Get-AzPrivateEndpointConnection -PrivateLinkResourceId $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="Cassandra"
Check="Private endpoint configured"
Resource=$name
Status=if($pe){"PASS"}else{"FAIL"}
Details=if($pe){"Private endpoint exists"}else{"No private endpoint"}
}

# Managed Identity
$identity = $details.Identity.Type
$results += [PSCustomObject]@{
Category="Cassandra"
Check="Managed identity enabled"
Resource=$name
Status=if($identity){"PASS"}else{"FAIL"}
Details=if($identity){"Identity: $identity"}else{"No identity"}
}

# Encryption (Always ON → informational PASS)
$results += [PSCustomObject]@{
Category="Cassandra"
Check="Encryption at rest enabled"
Resource=$name
Status="PASS"
Details="Azure-managed encryption enabled by default"
}

# Diagnostic Logs
$diag = Get-AzDiagnosticSetting -ResourceId $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="Cassandra"
Check="Diagnostic logs enabled"
Resource=$name
Status=if($diag){"PASS"}else{"WARN"}
Details=if($diag){"Configured"}else{"Not configured"}
}

# RBAC
$roles = Get-AzRoleAssignment -Scope $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="Cassandra"
Check="RBAC configured"
Resource=$name
Status=if($roles){"PASS"}else{"WARN"}
Details=if($roles){"Roles assigned"}else{"No roles"}
}

}

}

}catch{

$results += [PSCustomObject]@{
Category="Cassandra"
Check="Cassandra scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}

# ============================================================
# Azure Confidential Ledger Security Checks
# ============================================================

try {

$ledgers = Get-AzResource -ResourceType "Microsoft.ConfidentialLedger/ledgers"

if (-not $ledgers -or $ledgers.Count -eq 0) {

    $results += [PSCustomObject]@{
        Category="ConfidentialLedger"
        Check="Ledger instances"
        Resource="Subscription"
        Status="INFO"
        Details="No Confidential Ledger instances found"
    }

} else {

foreach ($ledger in $ledgers) {

$name = $ledger.Name
$resourceId = $ledger.ResourceId

$details = Get-AzResource -ResourceId $resourceId -ExpandProperties

# Public Access
$publicAccess = $details.Properties.publicNetworkAccess
$results += [PSCustomObject]@{
Category="ConfidentialLedger"
Check="Public network access disabled"
Resource=$name
Status=if($publicAccess -eq "Disabled"){"PASS"}else{"FAIL"}
Details="Public Access: $publicAccess"
}

# Private Endpoint
$pe = Get-AzPrivateEndpointConnection -PrivateLinkResourceId $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="ConfidentialLedger"
Check="Private endpoint configured"
Resource=$name
Status=if($pe){"PASS"}else{"FAIL"}
Details=if($pe){"Private endpoint exists"}else{"No private endpoint"}
}

# Managed Identity
$identity = $details.Identity.Type
$results += [PSCustomObject]@{
Category="ConfidentialLedger"
Check="Managed identity enabled"
Resource=$name
Status=if($identity){"PASS"}else{"FAIL"}
Details=if($identity){"Identity: $identity"}else{"No identity"}
}

# Diagnostic Logs
$diag = Get-AzDiagnosticSetting -ResourceId $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="ConfidentialLedger"
Check="Diagnostic logs enabled"
Resource=$name
Status=if($diag){"PASS"}else{"WARN"}
Details=if($diag){"Configured"}else{"Not configured"}
}

# RBAC
$roles = Get-AzRoleAssignment -Scope $resourceId -ErrorAction SilentlyContinue
$results += [PSCustomObject]@{
Category="ConfidentialLedger"
Check="RBAC configured"
Resource=$name
Status=if($roles){"PASS"}else{"WARN"}
Details=if($roles){"Roles assigned"}else{"No roles"}
}

# Secure Transport (Always enforced)
$results += [PSCustomObject]@{
Category="ConfidentialLedger"
Check="Secure transport enforced"
Resource=$name
Status="PASS"
Details="TLS enforced by Azure service"
}

}

}

}catch{

$results += [PSCustomObject]@{
Category="ConfidentialLedger"
Check="Ledger scan"
Resource="N/A"
Status="ERROR"
Details=$_.Exception.Message
}

}






# ── Generate Report ─────────────────────────────────────────
Write-Host "Generating HTML report..." -ForegroundColor Cyan
$rows = ""
foreach ($r in $results) {
    $color = switch ($r.Status) { "PASS"{"#00c87a"} "FAIL"{"#ff4d6d"} "WARN"{"#ffab40"} "INFO"{"#50e6ff"} default{"#8892a4"} }
    $icon  = switch ($r.Status) { "PASS"{"✔"} "FAIL"{"✘"} "WARN"{"⚠"} default{"ℹ"} }
    $rows += "<tr><td>$($r.Category)</td><td>$($r.Check)</td><td>$($r.Resource)</td><td style='color:$color;font-weight:700'>$icon $($r.Status)</td><td>$($r.Details)</td></tr>"
}

$pass = ($results | Where-Object Status -eq "PASS").Count
$fail = ($results | Where-Object Status -eq "FAIL").Count
$warn = ($results | Where-Object Status -eq "WARN").Count
$total = $results.Count

$html = Get-HtmlTemplate -Title "Storage Security Audit" -SubName $subName -Date $date -Rows $rows -Pass $pass -Fail $fail -Warn $warn -Total $total
$html | Out-File "AzureStorage_Report.html" -Encoding UTF8

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " ✅ Report Ready: AzureStorage_Report.html" -ForegroundColor Green
Write-Host " 📥 Downloading automatically..." -ForegroundColor Yellow
Write-Host "========================================" -ForegroundColor Cyan
download AzureStorage_Report.html
